# Generated by Django 4.2.1 on 2023-05-20 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_employee_status_alter_employee_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dateCreated',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
