# Generated by Django 4.2.1 on 2023-05-22 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_alter_employee_datecreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(max_length=12)),
                ('reason', models.CharField(max_length=1500)),
                ('dateCreated', models.DateField(default=datetime.date.today, null=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.employee')),
            ],
        ),
    ]
