# Generated by Django 4.2.1 on 2023-05-19 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(error_messages={'null': 'ID field cannot be null', 'unique': 'This ID is already in use'}, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=6)),
                ('availableVacation', models.IntegerField()),
                ('approvedVacation', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
