# Generated by Django 4.2.1 on 2023-05-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_alter_employee_approvedvacation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='mobile',
            new_name='number',
        ),
    ]
