# Generated by Django 4.2.1 on 2023-05-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_vacation'),
        ('Management', '0005_rename_mobile_employee_number'),
    ]

    operations = [
    ]
